name = "WannierIO"
uuid = "cb1bc77f-5443-4951-af9f-05b616a3e422"
authors = ["Junfeng Qiao <qiaojunfeng@outlook.com>"]
version = "0.2.6"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
EzXML = "8f5d6c58-4d21-5cfd-889c-e3ad7ee6a615"
FortranFiles = "c58ffaec-ab22-586d-bfc5-781a99fd0b10"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"

[compat]
DelimitedFiles = "1"
DocStringExtensions = "0.9"
EzXML = "1.1.0"
FortranFiles = "0.6.0"
OrderedCollections = "1.8.0"
StaticArrays = "1"
TOML = "1"
julia = "1.8"
